-- MySQL Script generated by MySQL Workbench
-- Thu May 30 18:45:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema psigram
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `psigram` ;

-- -----------------------------------------------------
-- Schema psigram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psigram` DEFAULT CHARACTER SET utf8 ;
USE `psigram` ;

-- -----------------------------------------------------
-- Table `psigram`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psigram`.`User` ;

CREATE TABLE IF NOT EXISTS `psigram`.`User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `type` VARCHAR(1) NOT NULL DEFAULT 'u' COMMENT 'u - user\na - admin\nb - business',
  `profile_picture_path` VARCHAR(256) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psigram`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psigram`.`Post` ;

CREATE TABLE IF NOT EXISTS `psigram`.`Post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `image_name` VARCHAR(256) NOT NULL,
  `sponsored` TINYINT NOT NULL DEFAULT 0,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_Post_User_idx` (`id_user` ASC),
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `psigram`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psigram`.`Like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psigram`.`Like` ;

CREATE TABLE IF NOT EXISTS `psigram`.`Like` (
  `id_user` INT NOT NULL,
  `id_post` INT NOT NULL,
  INDEX `fk_Like_User_idx` (`id_user` ASC),
  INDEX `fk_Like_Post_idx` (`id_post` ASC),
  CONSTRAINT `fk_Like_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `psigram`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like_Post`
    FOREIGN KEY (`id_post`)
    REFERENCES `psigram`.`Post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psigram`.`Follows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psigram`.`Follows` ;

CREATE TABLE IF NOT EXISTS `psigram`.`Follows` (
  `id_user_following` INT NOT NULL,
  `id_user_followed` INT NOT NULL,
  INDEX `fk_Follows_User1_idx` (`id_user_following` ASC),
  INDEX `fk_Follows_User2_idx` (`id_user_followed` ASC),
  CONSTRAINT `fk_Follows_User1`
    FOREIGN KEY (`id_user_following`)
    REFERENCES `psigram`.`User` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Follows_User2`
    FOREIGN KEY (`id_user_followed`)
    REFERENCES `psigram`.`User` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psigram`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psigram`.`Comment` ;

CREATE TABLE IF NOT EXISTS `psigram`.`Comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `text` VARCHAR(256) NOT NULL,
  `id_user` INT NOT NULL,
  `id_post` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_Comment_User_idx` (`id_user` ASC),
  INDEX `fk_Comment_Post_idx` (`id_post` ASC),
  CONSTRAINT `fk_Comment_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `psigram`.`User` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Comment_Post`
    FOREIGN KEY (`id_post`)
    REFERENCES `psigram`.`Post` (`id_post`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `psigram`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `psigram`;
INSERT INTO `psigram`.`User` (`id_user`, `username`, `password`, `name`, `surname`, `email`, `date_of_birth`, `gender`, `type`, `profile_picture_path`) VALUES (DEFAULT, 'a', 'a', 'Admin', 'Adminic', 'kosta.bizetic@gmail.com', '1997-12-19', 'm', 'a', NULL);
INSERT INTO `psigram`.`User` (`id_user`, `username`, `password`, `name`, `surname`, `email`, `date_of_birth`, `gender`, `type`, `profile_picture_path`) VALUES (DEFAULT, 'u', 'u', 'User', 'Useric', 'ldojcilovic@gmail.com', '1997-11-12', 'm', 'u', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `psigram`.`Post`
-- -----------------------------------------------------
START TRANSACTION;
USE `psigram`;
INSERT INTO `psigram`.`Post` (`id_post`, `timestamp`, `image_name`, `sponsored`, `id_user`) VALUES (1, '2019-05-30 18:24:26', 'u_1559233466.jpg', 0, 2);
INSERT INTO `psigram`.`Post` (`id_post`, `timestamp`, `image_name`, `sponsored`, `id_user`) VALUES (2, '2019-05-30 18:24:32', 'u_1559233472.jpg', 0, 2);

COMMIT;

